# Generated by Django 4.2.28 on 2026-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
