# Generated by Django 4.2.28 on 2026-03-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Uploaded Video')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo URL or video file URL', max_length=500),
        ),
    ]
