# Generated by Django 4.2.28 on 2026-03-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_has_video_testimonial_video_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video file', null=True, upload_to='testimonials/videos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('mp4_url', 'MP4 URL'), ('mp4_file', 'MP4 File Upload')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo URL or MP4 video URL', max_length=500),
        ),
    ]
