# Generated by Django 4.2.28 on 2026-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonial_video_file_alter_testimonial_video_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for notification purposes', max_length=254),
        ),
    ]
