# Generated by Django 4.2.7 on 2026-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_shipping_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("razorpay", "Razorpay"),
                    ("card", "Credit/Debit Card"),
                    ("upi", "UPI"),
                    ("netbanking", "Net Banking"),
                    ("simulated", "Simulated (Dev/Test)"),
                ],
                max_length=20,
            ),
        ),
    ]
