# Generated by Django 4.2.29 on 2026-04-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookpurchase',
            name='order_id',
        ),
        migrations.AddField(
            model_name='cartcheckoutsession',
            name='payu_order_id',
            field=models.CharField(blank=True, help_text='PayU transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebookpurchase',
            name='payu_order_id',
            field=models.CharField(blank=True, help_text='PayU transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebookpurchase',
            name='payu_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebookpurchase',
            name='payu_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payu_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payu_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payu_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payu_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payu_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payu_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cartcheckoutsession',
            name='cashfree_order_id',
            field=models.CharField(blank=True, help_text='Cashfree order ID (legacy)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebookpurchase',
            name='cashfree_order_id',
            field=models.CharField(blank=True, help_text='Cashfree order ID (legacy)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebookpurchase',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID (legacy)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('payu', 'PayU'), ('simulated', 'Simulated (Dev/Test)')], max_length=20),
        ),
    ]
