# Generated by Django 5.1.15 on 2026-03-21 08:36

import apps.books.cloudinary_storage
import apps.books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_revert_cover_image_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.books.cloudinary_storage.RawCloudinaryStorage(),
                upload_to='books/pdfs/',
                validators=[
                    apps.books.validators.validate_pdf_type,
                    apps.books.validators.validate_pdf_size,
                ],
            ),
        ),
    ]
