# Generated by Django 4.2.7 on 2026-03-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ["-created_at"]},
        ),
    ]
