# Generated by Django 4.2.28 on 2026-02-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_type_book_ebook_price_book_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
