# Generated by Django 4.2.28 on 2026-03-04 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('book_title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='book_submissions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book Submission',
                'verbose_name_plural': 'Book Submissions',
                'db_table': 'book_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
