# Generated by Django 4.2.29 on 2026-03-12 06:13

import apps.books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of physical copies in stock'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/', validators=[apps.books.validators.validate_image_type, apps.books.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/', validators=[apps.books.validators.validate_pdf_type, apps.books.validators.validate_pdf_size]),
        ),
    ]
